apiVersion: v1
kind: Service
metadata:
  name: gamenet-service
spec:
  selector:
    app: gamenet
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer  # Use LoadBalancer for external access, NodePort for internal
